import { THREAD_TITLES_HOST_EXTENSION_ID } from "../../shared/thread-titles-protocol.js";
import { parseSkillEnvelope } from "../../shared/skill-envelope.js";
import type { HostExtension, HostExtensionContext } from "../host-extensions.js";
import { cleanThreadTitle, textFromContent, visibleTitleText } from "../host-messages.js";

interface TitleMessage {
  role?: string;
  content?: unknown;
  skill?: { name?: unknown; command?: unknown };
}

function titleVisibleUserText(text: string, metadata: TitleMessage["skill"]): string {
  const envelope = parseSkillEnvelope(text);
  if (envelope && metadata
    && metadata.name === envelope.name
    && typeof metadata.command === "string"
    && metadata.command.replace(/^\/skill:/u, "").replace(/^\//u, "") === envelope.name) {
    return envelope.userMessage;
  }
  return visibleTitleText(text);
}

/** The first exchanges, rendered as the prompt a title model reads. */
export function buildTitleConversation(
  runtimeMessages: readonly TitleMessage[],
  persistedMessages: readonly TitleMessage[] = [],
): string {
  function render(messages: readonly TitleMessage[]): string {
    return messages
      .filter((message) => message.role === "user" || message.role === "assistant")
      .map((message) => {
        const text = textFromContent(message.content);
        return `${message.role}: ${message.role === "user" ? titleVisibleUserText(text, message.skill) : text}`;
      })
      .filter((line) => line.trim().length > line.indexOf(":") + 1)
      .slice(0, 4)
      .join("\n\n")
      .slice(0, 6000);
  }
  return render(runtimeMessages) || render(persistedMessages);
}

const record = (input: unknown): Record<string, unknown> =>
  input && typeof input === "object" ? input as Record<string, unknown> : {};

/**
 * Thread Title Generator's host entry. It titles a thread with a model the
 * desktop side chose; renaming itself stays a core action.
 */
export function createThreadTitlesHostExtension(): HostExtension {
  return {
    id: THREAD_TITLES_HOST_EXTENSION_ID,
    name: "Thread Title Generator",
    activate(context: HostExtensionContext) {
      const { services } = context;
      context.registerCommand("generate", async (input) => {
        const fields = record(input);
        const provider = typeof fields.provider === "string" ? fields.provider : "";
        const modelId = typeof fields.modelId === "string" ? fields.modelId : "";
        const force = fields.force === true;
        const sessionId = typeof fields.sessionId === "string" ? fields.sessionId : undefined;
        const prompt = typeof fields.prompt === "string" ? fields.prompt : "";
        if (!provider || !modelId) throw new Error("Title generation needs a provider and a model.");

        if (services.runtimeOwner() === "pi") {
          if (!force) return undefined;
          throw new Error("Generate the thread title in Pi while Tau is attached to its runtime.");
        }
        const thread = services.thread(sessionId);
        if (!thread) {
          throw new Error(sessionId ? "That thread is not open any more. Open it again to continue." : "Pi runtime is not ready");
        }
        if (thread.backendKind !== "pi") throw new Error("Claude Code thread titles are generated by the Claude backend and cannot use Pi's model runtime.");
        if (force && thread.isStreaming()) throw new Error("Wait for the active agent run before generating a title.");
        if (thread.sessionName() && !force) return undefined;
        // An automatic title must not wait for the run: agentic first turns take
        // minutes, and the prompt alone names the thread well enough. The
        // prompt stands in while the transcript has not persisted it yet.
        const conversation = buildTitleConversation(
          (await thread.transcript()).map((message) => ({ role: message.role, content: message.text })),
          [{ role: "user", content: prompt }],
        );
        if (!conversation) {
          if (!force) return undefined;
          throw new Error("The thread has no conversation to title yet.");
        }

        services.log("title.started", `${provider}/${modelId}`);
        const title = cleanThreadTitle(await thread.completeTitle(provider, modelId, conversation));
        if (!thread.isCurrent()) return undefined;
        await services.setThreadTitle(thread.sessionId, title, "generated");
        services.log("title.generated", title);
        return { title };
      });
    },
  };
}
