// What the icon generator writes, as text: the SVGs it rasterises and the files it
// writes as they are (Android vectors, the Icon Composer document, asset catalogs,
// the web manifest). Pure functions over the sources in assets/icon/, so a test
// can check the committed text files without rendering anything.

export const COLOURS = {
  plateTop: "#5c87d6",
  plateBottom: "#4670c0",
  paper: "#fbfaf8",
  blueDark: "#6b93e0",
  nightTop: "#232322",
  nightBottom: "#11110f",
  // K69's document surfaces; the splash screens sit on them.
  lightSurface: "#fbfaf8",
  darkSurface: "#1a1a19",
};

/** The τ's strokes in an SVG: every path with a stroke width. */
export function readStrokes(svg) {
  return [...svg.matchAll(/<path\b[^>]*>/gu)].flatMap(([tag]) => {
    const attribute = (name) => tag.match(new RegExp(`\\s${name}="([^"]*)"`, "u"))?.[1];
    const width = attribute("stroke-width");
    return width ? [{ d: attribute("d"), width: Number(width), colour: attribute("stroke") }] : [];
  });
}

/** Everything inside the root element except its title. */
export function svgBody(svg) {
  const start = svg.indexOf(">", svg.indexOf("<svg")) + 1;
  return svg.slice(start, svg.lastIndexOf("</svg>")).replace(/<title>[^<]*<\/title>/u, "").trim();
}

const svgRoot = (width, height, body, viewBox = `0 0 ${width} ${height}`) =>
  `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="${viewBox}">\n${body}\n</svg>\n`;

const strokePaths = (strokes, colour, transform = "") => {
  const paths = strokes.map((stroke) =>
    `<path d="${stroke.d}" fill="none" stroke="${colour ?? stroke.colour}" stroke-width="${stroke.width}" stroke-linecap="round" stroke-linejoin="round"/>`).join("\n");
  return transform ? `<g transform="${transform}">\n${paths}\n</g>` : paths;
};

/** A 1024 source cut to a shape: `round` (Android's legacy round icon) or a rounded square. */
export function clippedSvg(source, shape) {
  const clip = shape === "round"
    ? `<circle cx="512" cy="512" r="469"/>`
    : `<rect x="43" y="43" width="938" height="938" rx="170"/>`;
  return svgRoot(1024, 1024, `<defs><clipPath id="shape">${clip}</clipPath></defs>\n<g clip-path="url(#shape)">\n${svgBody(source)}\n</g>`);
}

/** iOS 18's tinted icon: the full-bleed τ in white on black; the system tints the grey. */
export function tintedSvg(square) {
  return svgRoot(1024, 1024, `<rect width="1024" height="1024" fill="#000"/>\n${strokePaths(readStrokes(square), "#fff")}`);
}

/** A splash screen: the macOS-grid icon centred on a surface, a fifth of the short side. */
export function splashSvg(icon, width, height, surface) {
  const size = Math.round(Math.min(width, height) * 0.2);
  const x = Math.round((width - size) / 2), y = Math.round((height - size) / 2);
  return svgRoot(width, height,
    `<rect width="${width}" height="${height}" fill="${surface}"/>\n<svg x="${x}" y="${y}" width="${size}" height="${size}" viewBox="0 0 1024 1024">\n${svgBody(icon)}\n</svg>`);
}

// ------------------------------------------------------------------ Android

const ANDROID_NS = `xmlns:android="http://schemas.android.com/apk/res/android"`;
const argb = (hex) => `#FF${hex.slice(1).toUpperCase()}`;

function androidVector(paths, extraNs = "") {
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/icons/generate.mjs from assets/icon/; edit the SVGs, not this file. -->
<vector ${ANDROID_NS}${extraNs}
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="1024"
    android:viewportHeight="1024">
${paths}
</vector>
`;
}

const androidStrokes = (strokes, colour) => strokes.map((stroke) => `    <path
        android:pathData="${stroke.d}"
        android:strokeColor="${argb(colour)}"
        android:strokeWidth="${stroke.width}"
        android:strokeLineCap="round"
        android:strokeLineJoin="round" />`).join("\n");

/** The adaptive icon's foreground: the τ inside the 66 dp safe circle. */
export function androidForeground(foregroundSvg) {
  return androidVector(androidStrokes(readStrokes(foregroundSvg), COLOURS.paper));
}

/** Android 13's themed icon: the same τ, one opaque colour; the launcher tints it. */
export function androidMonochrome(foregroundSvg) {
  return androidVector(androidStrokes(readStrokes(foregroundSvg), "#ffffff"));
}

/** The adaptive icon's background: the plate's gradient, as on the other platforms. */
export function androidBackground() {
  return androidVector(`    <path android:pathData="M0,0h1024v1024h-1024z">
        <aapt:attr name="android:fillColor">
            <gradient
                android:type="linear"
                android:startX="0"
                android:startY="0"
                android:endX="0"
                android:endY="1024">
                <item android:offset="0" android:color="${argb(COLOURS.plateTop)}" />
                <item android:offset="1" android:color="${argb(COLOURS.plateBottom)}" />
            </gradient>
        </aapt:attr>
    </path>`, `\n    xmlns:aapt="http://schemas.android.com/aapt"`);
}

export const ANDROID_LAUNCHER = { mdpi: 48, hdpi: 72, xhdpi: 96, xxhdpi: 144, xxxhdpi: 192 };

/** The splash drawables Capacitor's template names, with their pixel sizes. */
export const ANDROID_SPLASH = [
  ["drawable", 480, 320],
  ...Object.entries({ mdpi: [320, 480], hdpi: [480, 800], xhdpi: [720, 1280], xxhdpi: [960, 1600], xxxhdpi: [1280, 1920] })
    .flatMap(([density, [w, h]]) => [[`drawable-port-${density}`, w, h], [`drawable-land-${density}`, h, w]]),
];

/** `drawable-port-xhdpi` → `drawable-port-night-xhdpi`: night sits after orientation. */
export function nightFolder(folder) {
  const parts = folder.split("-");
  const at = parts[1] === "port" || parts[1] === "land" ? 2 : 1;
  parts.splice(at, 0, "night");
  return parts.join("-");
}

// ------------------------------------------------------------------ Apple

const srgb = (hex) => "srgb:" + [1, 3, 5].map((i) => (parseInt(hex.slice(i, i + 2), 16) / 255).toFixed(5)).join(",") + ",1.00000";

function centreline(d) {
  const numbers = (text) => text.trim().split(/[\s,]+/u).map(Number);
  const points = [];
  let current;
  for (const [, command, args] of d.matchAll(/([MLC])([^MLC]*)/gu)) {
    const values = numbers(args);
    if (command === "M" || command === "L") {
      current = [values[0], values[1]];
      points.push(current);
      continue;
    }
    const [p0, p1, p2, p3] = [current, [values[0], values[1]], [values[2], values[3]], [values[4], values[5]]];
    for (let step = 1; step <= 64; step++) {
      const t = step / 64, u = 1 - t;
      points.push([0, 1].map((axis) => u ** 3 * p0[axis] + 3 * u * u * t * p1[axis] + 3 * u * t * t * p2[axis] + t ** 3 * p3[axis]));
    }
    current = p3;
  }
  return points;
}

const round2 = (value) => Math.round(value * 100) / 100;

/**
 * A round-capped stroke as a filled outline. Icon Composer colours a layer's shapes
 * by filling them, and actool's icns renderer fills an open stroke's inside too.
 */
export function strokeOutline(stroke, scale = 1, offset = [0, 0]) {
  const points = centreline(stroke.d).map(([x, y]) => [(x + offset[0]) * scale, (y + offset[1]) * scale]);
  const r = (stroke.width * scale) / 2;
  const normal = (index) => {
    const [a, b] = [points[Math.max(0, index - 1)], points[Math.min(points.length - 1, index + 1)]];
    const [dx, dy] = [b[0] - a[0], b[1] - a[1]];
    const length = Math.hypot(dx, dy);
    return [-dy / length, dx / length];
  };
  const side = (sign) => points.map((point, index) => {
    const [nx, ny] = normal(index);
    return `${round2(point[0] + sign * nx * r)} ${round2(point[1] + sign * ny * r)}`;
  });
  const left = side(1), right = side(-1).reverse();
  const arc = `A${round2(r)} ${round2(r)} 0 0 0 `;
  return `M${left[0]}L${left.slice(1).join("L")}${arc}${right[0]}L${right.slice(1).join("L")}${arc}${left[0]}Z`;
}

/**
 * The Icon Composer layer: the τ from the macOS-grid icon, scaled from Apple's 824 grid
 * to the document's 1024 canvas, as filled outlines in the given colour.
 */
export function iconComposerGlyph(iconLight, colour) {
  const paths = readStrokes(iconLight).map((stroke) => `<path d="${strokeOutline(stroke, 1024 / 824, [-100, -100])}" fill="${colour}"/>`);
  return svgRoot(1024, 1024, paths.join("\n"));
}

/** macOS 26's icon document (`.icon`); electron-builder compiles it with actool. */
export function iconComposerDocument() {
  const gradient = (top, bottom) => ({ "linear-gradient": [srgb(top), srgb(bottom)] });
  return JSON.stringify({
    "fill-specializations": [
      { value: gradient(COLOURS.plateTop, COLOURS.plateBottom) },
      { appearance: "dark", value: gradient(COLOURS.nightTop, COLOURS.nightBottom) },
    ],
    groups: [{
      layers: [{
        "image-name-specializations": [{ value: "tau.svg" }, { appearance: "dark", value: "tau-dark.svg" }],
        name: "tau",
      }],
      shadow: { kind: "neutral", opacity: 0.5 },
      translucency: { enabled: true, value: 0.5 },
    }],
    "supported-platforms": { squares: ["macOS"] },
  }, null, 2) + "\n";
}

const catalog = (images) => JSON.stringify({ images, info: { author: "xcode", version: 1 } }, null, 2) + "\n";

/** iOS 18 app icon: default, dark and tinted, each one 1024 image. */
export function iosAppIconContents() {
  const image = (filename, appearance) => ({
    ...(appearance ? { appearances: [{ appearance: "luminosity", value: appearance }] } : {}),
    filename, idiom: "universal", platform: "ios", size: "1024x1024",
  });
  return catalog([image("AppIcon-1024.png"), image("AppIcon-1024-dark.png", "dark"), image("AppIcon-1024-tinted.png", "tinted")]);
}

/** The launch storyboard's image: one 2732 picture per appearance, used at every scale. */
export function iosSplashContents() {
  const dark = [{ appearance: "luminosity", value: "dark" }];
  return catalog(["1x", "2x", "3x"].flatMap((scale) => [
    { filename: "splash.png", idiom: "universal", scale },
    { appearances: dark, filename: "splash-dark.png", idiom: "universal", scale },
  ]));
}

// ------------------------------------------------------------------ web

/** The web app manifest the browser and the phone clients link; paths are relative to it. */
export function webManifest() {
  return JSON.stringify({
    name: "Tau",
    short_name: "Tau",
    start_url: "./",
    scope: "./",
    display: "standalone",
    background_color: COLOURS.lightSurface,
    theme_color: COLOURS.lightSurface,
    icons: [
      { src: "icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
      { src: "favicon.svg", sizes: "any", type: "image/svg+xml", purpose: "any" },
    ],
  }, null, 2) + "\n";
}
