// The three winget manifests for a release, kept in packaging/winget/. A pull
// request to microsoft/winget-pkgs copies them to manifests/r/Rasalas/Tau/<version>/
// (docs/RELEASE.md); `npm run packaging:update` writes them with the other packages.
import { REPO } from "./release.mjs";

export const PACKAGE_ID = "Rasalas.Tau";
export const MANIFEST_VERSION = "1.9.0";
export const WINGET_DIR = "packaging/winget";

function header(type) {
  return `# Generated by scripts/packaging/update-winget.mjs
# yaml-language-server: $schema=https://aka.ms/winget-manifest.${type}.${MANIFEST_VERSION}.schema.json
`;
}

/** The manifest triple by file name: version, installer, default locale. */
export function renderWingetManifests(assets) {
  const identity = `PackageIdentifier: ${PACKAGE_ID}\nPackageVersion: ${assets.version}\n`;
  const footer = (type) => `ManifestType: ${type}\nManifestVersion: ${MANIFEST_VERSION}\n`;
  const releaseDate = assets.publishedAt.slice(0, 10);
  return {
    [`${PACKAGE_ID}.yaml`]: `${header("version")}
${identity}DefaultLocale: en-US
${footer("version")}`,
    [`${PACKAGE_ID}.installer.yaml`]: `${header("installer")}
${identity}InstallerType: nullsoft
# electron-builder's assisted NSIS installer installs for the current user unless told otherwise.
Scope: user
UpgradeBehavior: install
${releaseDate ? `ReleaseDate: ${releaseDate}\n` : ""}Installers:
  - Architecture: x64
    InstallerUrl: ${assets.exe.url}
    InstallerSha256: ${assets.exe.sha256.toUpperCase()}
${footer("installer")}`,
    [`${PACKAGE_ID}.locale.en-US.yaml`]: `${header("defaultLocale")}
${identity}PackageLocale: en-US
Publisher: Torben Buck
PublisherUrl: https://github.com/Rasalas
PublisherSupportUrl: https://github.com/${REPO}/issues
PackageName: Tau
PackageUrl: https://github.com/${REPO}
License: MIT
LicenseUrl: https://github.com/${REPO}/blob/main/LICENSE
ShortDescription: Desktop workbench for the Pi coding agent.
Moniker: tau
Tags:
  - ai
  - coding-agent
  - developer-tools
  - electron
ReleaseNotesUrl: ${assets.notesUrl}
${footer("defaultLocale")}`,
  };
}

