// packaging/homebrew/tau.rb for a release: the version and the SHA-256 of both
// disk images. The tap holds a copy of this file (docs/RELEASE.md);
// `npm run packaging:update` writes it with the other packages.
export const CASK_PATH = "packaging/homebrew/tau.rb";

/** An asset's URL with the version left to the cask, so `brew livecheck` and a bump touch one line. */
function caskUrl(assets, asset) {
  return asset.url.replaceAll(assets.version, "#{version}");
}

export function renderCask(assets) {
  return `# Generated by scripts/packaging/update-cask.mjs; the tap's Casks/tau.rb is a copy.
cask "tau" do
  version "${assets.version}"

  on_arm do
    sha256 "${assets.dmgArm64.sha256}"

    url "${caskUrl(assets, assets.dmgArm64)}"
  end
  on_intel do
    sha256 "${assets.dmgX64.sha256}"

    url "${caskUrl(assets, assets.dmgX64)}"
  end

  name "Tau"
  desc "Desktop workbench for the Pi coding agent"
  homepage "${assets.repoUrl}"

  livecheck do
    url :url
    strategy :github_latest
  end

  # Tau updates itself; \`brew upgrade\` leaves it alone unless asked with --greedy.
  auto_updates true
  # Electron 44's LSMinimumSystemVersion is 13.0.
  depends_on macos: ">= :ventura"

  app "Tau.app"

  zap trash: [
    "~/.tau",
    "~/Library/Application Support/tau-pi-desktop-prototype",
    "~/Library/Caches/de.tbuck.tau",
    "~/Library/Caches/de.tbuck.tau.ShipIt",
    "~/Library/Caches/dev.tbuck.tau",
    "~/Library/Caches/dev.tbuck.tau.ShipIt",
    "~/Library/Caches/tau-pi-desktop-prototype-updater",
    "~/Library/Preferences/de.tbuck.tau.plist",
    "~/Library/Preferences/dev.tbuck.tau.plist",
    "~/Library/Saved Application State/de.tbuck.tau.savedState",
    "~/Library/Saved Application State/dev.tbuck.tau.savedState",
  ]

end
`;
}
