// packaging/aur/tau-bin/PKGBUILD and its .SRCINFO for a release. The package
// repacks the release's x86_64 AppImage; the AUR repository holds a copy of both
// files (docs/RELEASE.md), and `npm run packaging:update` writes them with the
// other packages. `makepkg --printsrcinfo` on Arch prints the same .SRCINFO.
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { REPO, ROOT } from "./release.mjs";

export const PKGNAME = "tau-bin";
export const AUR_DIR = `packaging/aur/${PKGNAME}`;

const PKGDESC = "Desktop workbench for the Pi coding agent";
const URL = `https://github.com/${REPO}`;
/** What Electron's own binary links against and does not carry in the AppImage. */
const DEPENDS = [
  "alsa-lib", "at-spi2-core", "gtk3", "libcups", "libdrm", "libxcomposite", "libxdamage",
  "libxkbcommon", "libxrandr", "mesa", "nss", "xdg-utils",
];
const OPTDEPENDS = [
  "git: the Review, worktrees and checkpoints",
  "github-cli: pull requests from the Changes panel",
  "nodejs: `tau app <path>` from a terminal (resources/app.asar.unpacked/bin/tau.mjs)",
];
/** tau-editor, the GTK front end of xi, also installs /usr/bin/tau. */
const CONFLICTS = ["tau", "tau-editor"];
const OPTIONS = ["!debug", "!strip"];

export function licenseSha256(root = ROOT) {
  return createHash("sha256").update(readFileSync(join(root, "LICENSE"))).digest("hex");
}

/** makepkg reads `-` as a separator in pkgver; a prerelease version would need `_`. */
function pkgver(version) {
  return version.replaceAll("-", "_");
}

const quoted = (values) => values.map((value) => `'${value}'`).join(" ");

export function renderPkgbuild(assets, license) {
  return `# Maintainer: Torben Buck
# Generated by scripts/packaging/update-aur.mjs from the GitHub release.

pkgname=${PKGNAME}
_version=${assets.version}
pkgver=${pkgver(assets.version)}
pkgrel=1
pkgdesc='${PKGDESC}'
arch=('x86_64')
url='${URL}'
license=('Apache-2.0')
depends=(${quoted(DEPENDS)})
optdepends=(
${OPTDEPENDS.map((entry) => `  '${entry}'`).join("\n")}
)
provides=('tau')
conflicts=(${quoted(CONFLICTS)})
options=(${quoted(OPTIONS)})

_appimage="Tau-\${_version}.AppImage"
noextract=("\${_appimage}")
source=(
  "\${_appimage}::${URL}/releases/download/v\${_version}/\${_appimage}"
  "LICENSE-\${_version}::https://raw.githubusercontent.com/${REPO}/v\${_version}/LICENSE"
)
sha256sums=('${assets.appImage.sha256}'
            '${license}')

prepare() {
  cd "\${srcdir}"
  chmod +x "\${_appimage}"
  rm -rf squashfs-root
  # Extraction needs no FUSE; the payload is what the AppImage would mount.
  "./\${_appimage}" --appimage-extract >/dev/null
}

package() {
  install -d "\${pkgdir}/opt/\${pkgname}"
  cp -a --no-preserve=ownership "\${srcdir}/squashfs-root/." "\${pkgdir}/opt/\${pkgname}/"
  chmod -R u=rwX,go=rX "\${pkgdir}/opt/\${pkgname}"
  # Chromium's setuid sandbox helper.
  chmod 4755 "\${pkgdir}/opt/\${pkgname}/chrome-sandbox"

  install -d "\${pkgdir}/usr/bin"
  printf '#!/bin/sh\\nexec /opt/%s/AppRun "$@"\\n' "\${pkgname}" > "\${pkgdir}/usr/bin/tau"
  chmod 755 "\${pkgdir}/usr/bin/tau"

  local icon size
  for icon in "\${srcdir}"/squashfs-root/usr/share/icons/hicolor/*/apps/tau.png; do
    size="\${icon%/apps/tau.png}"
    install -Dm644 "\${icon}" "\${pkgdir}/usr/share/icons/hicolor/\${size##*/}/apps/tau.png"
  done

  install -d "\${pkgdir}/usr/share/applications"
  cat > "\${pkgdir}/usr/share/applications/tau.desktop" <<EOF
[Desktop Entry]
Name=Tau
Comment=${PKGDESC}
Exec=tau %U
TryExec=tau
Terminal=false
Type=Application
Icon=tau
Categories=Development;
EOF

  install -Dm644 "\${srcdir}/LICENSE-\${_version}" "\${pkgdir}/usr/share/licenses/\${pkgname}/LICENSE"
}
`;
}

/** What `makepkg --printsrcinfo` prints for the PKGBUILD above. */
export function renderSrcinfo(assets, license) {
  const appimage = `Tau-${assets.version}.AppImage`;
  const lines = [
    `pkgbase = ${PKGNAME}`,
    `pkgdesc = ${PKGDESC}`,
    `pkgver = ${pkgver(assets.version)}`,
    "pkgrel = 1",
    `url = ${URL}`,
    "arch = x86_64",
    "license = Apache-2.0",
    ...DEPENDS.map((entry) => `depends = ${entry}`),
    ...OPTDEPENDS.map((entry) => `optdepends = ${entry}`),
    "provides = tau",
    ...CONFLICTS.map((entry) => `conflicts = ${entry}`),
    `noextract = ${appimage}`,
    ...OPTIONS.map((entry) => `options = ${entry}`),
    `source = ${appimage}::${URL}/releases/download/v${assets.version}/${appimage}`,
    `source = LICENSE-${assets.version}::https://raw.githubusercontent.com/${REPO}/v${assets.version}/LICENSE`,
    `sha256sums = ${assets.appImage.sha256}`,
    `sha256sums = ${license}`,
  ];
  return `${lines[0]}\n${lines.slice(1).map((line) => `\t${line}`).join("\n")}\n\npkgname = ${PKGNAME}\n`;
}

