# Generated by scripts/packaging/update-cask.mjs; the tap's Casks/tau.rb is a copy.
cask "tau" do
  version "0.4.0"

  on_arm do
    sha256 "1b8b5745e9dfcc86ce5d1093607487c027ec6412b32601a5d80b54448d528266"

    url "https://github.com/Rasalas/tau/releases/download/v#{version}/Tau-#{version}-arm64.dmg"
  end
  on_intel do
    sha256 "aab3451c38ea078a224f39f1e4bfe5f412026b99dec804220e0707b2d514f868"

    url "https://github.com/Rasalas/tau/releases/download/v#{version}/Tau-#{version}.dmg"
  end

  name "Tau"
  desc "Desktop workbench for the Pi coding agent"
  homepage "https://github.com/Rasalas/tau"

  livecheck do
    url :url
    strategy :github_latest
  end

  # Tau updates itself; `brew upgrade` leaves it alone unless asked with --greedy.
  auto_updates true
  # Electron 44's LSMinimumSystemVersion is 13.0.
  depends_on macos: ">= :ventura"

  app "Tau.app"

  zap trash: [
    "~/.tau",
    "~/Library/Application Support/tau-pi-desktop-prototype",
    "~/Library/Caches/de.tbuck.tau",
    "~/Library/Caches/de.tbuck.tau.ShipIt",
    "~/Library/Caches/dev.tbuck.tau",
    "~/Library/Caches/dev.tbuck.tau.ShipIt",
    "~/Library/Caches/tau-pi-desktop-prototype-updater",
    "~/Library/Preferences/de.tbuck.tau.plist",
    "~/Library/Preferences/dev.tbuck.tau.plist",
    "~/Library/Saved Application State/de.tbuck.tau.savedState",
    "~/Library/Saved Application State/dev.tbuck.tau.savedState",
  ]

  caveats <<~EOS
    Tau is not signed yet. If macOS refuses to open it, allow it once under
    System Settings > Privacy & Security > Open Anyway, or run:
      xattr -dr com.apple.quarantine /Applications/Tau.app
  EOS
end
