# Generated by scripts/packaging/update-cask.mjs; the tap's Casks/tau.rb is a copy.
cask "tau" do
  version "0.7.35"

  on_arm do
    sha256 "4959fd872a3338d15d5a4e55232fdeb1ae9f371f961261d5a0f9c4507ca63cb2"

    url "https://github.com/Rasalas/tau-releases/releases/download/v#{version}/Tau-#{version}-arm64.dmg"
  end
  on_intel do
    sha256 "bab01ef561f41ed3c4ba91d3a71eba9a859835f34dc42e86905193e35ff36144"

    url "https://github.com/Rasalas/tau-releases/releases/download/v#{version}/Tau-#{version}.dmg"
  end

  name "Tau"
  desc "Desktop workbench for the Pi coding agent"
  homepage "https://github.com/Rasalas/tau-releases"

  livecheck do
    url :url
    strategy :github_latest
  end

  # Tau updates itself; `brew upgrade` leaves it alone unless asked with --greedy.
  auto_updates true
  # Electron 44's LSMinimumSystemVersion is 13.0.
  depends_on macos: ">= :ventura"

  app "Tau.app"

  zap trash: [
    "~/.tau",
    "~/Library/Application Support/tau-pi-desktop-prototype",
    "~/Library/Caches/de.tbuck.tau",
    "~/Library/Caches/de.tbuck.tau.ShipIt",
    "~/Library/Caches/dev.tbuck.tau",
    "~/Library/Caches/dev.tbuck.tau.ShipIt",
    "~/Library/Caches/tau-pi-desktop-prototype-updater",
    "~/Library/Preferences/de.tbuck.tau.plist",
    "~/Library/Preferences/dev.tbuck.tau.plist",
    "~/Library/Saved Application State/de.tbuck.tau.savedState",
    "~/Library/Saved Application State/dev.tbuck.tau.savedState",
  ]

end
