# Generated by scripts/packaging/update-cask.mjs; the tap's Casks/tau.rb is a copy.
cask "tau" do
  version "0.7.38"

  on_arm do
    sha256 "86b594544ff6d77a8563c5551e2b39d55c3f2c5d1848b504f07cf3a621817063"

    url "https://github.com/Rasalas/tau-releases/releases/download/v#{version}/Tau-#{version}-arm64.dmg"
  end
  on_intel do
    sha256 "93e10b6961017738cbbb2864d807883a00cba3c5d335bc2c735af54729ebf7d9"

    url "https://github.com/Rasalas/tau-releases/releases/download/v#{version}/Tau-#{version}.dmg"
  end

  name "Tau"
  desc "Desktop workbench for the Pi coding agent"
  homepage "https://github.com/Rasalas/tau-releases"

  livecheck do
    url :url
    strategy :github_latest
  end

  # Tau updates itself; `brew upgrade` leaves it alone unless asked with --greedy.
  auto_updates true
  # Electron 44's LSMinimumSystemVersion is 13.0.
  depends_on macos: ">= :ventura"

  app "Tau.app"

  zap trash: [
    "~/.tau",
    "~/Library/Application Support/tau-pi-desktop-prototype",
    "~/Library/Caches/de.tbuck.tau",
    "~/Library/Caches/de.tbuck.tau.ShipIt",
    "~/Library/Caches/dev.tbuck.tau",
    "~/Library/Caches/dev.tbuck.tau.ShipIt",
    "~/Library/Caches/tau-pi-desktop-prototype-updater",
    "~/Library/Preferences/de.tbuck.tau.plist",
    "~/Library/Preferences/dev.tbuck.tau.plist",
    "~/Library/Saved Application State/de.tbuck.tau.savedState",
    "~/Library/Saved Application State/dev.tbuck.tau.savedState",
  ]

end
