import { buildTitleConversation, cleanThreadTitle, type HostExtension, type HostExtensionContext } from "tau/host-extension";
import { THREAD_TITLES_HOST_EXTENSION_ID, TITLE_SYSTEM_PROMPT, TITLE_USER_PROMPT } from "./protocol.js";

const record = (input: unknown): Record<string, unknown> =>
  input && typeof input === "object" ? input as Record<string, unknown> : {};

/**
 * Thread Title Generator's host entry. It titles a thread with a model the
 * desktop side chose; renaming itself stays a core action.
 */
export function createThreadTitlesHostExtension(): HostExtension {
  return {
    id: THREAD_TITLES_HOST_EXTENSION_ID,
    name: "Thread Title Generator",
    permissions: ["sessions"],
    activate(context: HostExtensionContext) {
      const { services } = context;
      context.registerCommand("generate", async (input) => {
        const fields = record(input);
        const provider = typeof fields.provider === "string" ? fields.provider : "";
        const modelId = typeof fields.modelId === "string" ? fields.modelId : "";
        const force = fields.force === true;
        const sessionId = typeof fields.sessionId === "string" ? fields.sessionId : undefined;
        const prompt = typeof fields.prompt === "string" ? fields.prompt : "";
        if (!provider || !modelId) throw new Error("Title generation needs a provider and a model.");

        if (services.runtimeOwner() === "pi") {
          const attached = services.attachedRuntime(sessionId);
          if (!attached) throw new Error("The attached Pi runtime is not ready.");
          return attached.invoke(THREAD_TITLES_HOST_EXTENSION_ID, "generate", { provider, modelId, force });
        }
        const thread = services.thread(sessionId);
        if (!thread) {
          throw new Error(sessionId ? "That thread is not open any more. Open it again to continue." : "Pi runtime is not ready");
        }
        if (thread.backendKind !== "pi") throw new Error("Claude Code thread titles are generated by the Claude backend and cannot use Pi's model runtime.");
        if (force && thread.isStreaming()) throw new Error("Wait for the active agent run before generating a title.");
        if (thread.sessionName() && !force) return undefined;
        // An automatic title must not wait for the run: agentic first turns take
        // minutes, and the prompt alone names the thread well enough. The
        // prompt stands in while the transcript has not persisted it yet.
        const conversation = buildTitleConversation(
          (await thread.transcript()).map((message) => ({ role: message.role, content: message.text })),
          [{ role: "user", content: prompt }],
        );
        if (!conversation) {
          if (!force) return undefined;
          throw new Error("The thread has no conversation to title yet.");
        }

        services.log("title.started", `${provider}/${modelId}`);
        const title = cleanThreadTitle(await thread.complete(provider, modelId, {
          system: TITLE_SYSTEM_PROMPT,
          prompt: TITLE_USER_PROMPT(conversation),
          maxTokens: 48,
        }));
        if (!thread.isCurrent()) return undefined;
        await services.setThreadTitle(thread.sessionId, title, "generated");
        services.log("title.generated", title);
        return { title };
      });
    },
  };
}

export default createThreadTitlesHostExtension;
